//
//  EnglishLanguage.swift
//  NDP
//
//  Created by SapratigsMAC1 on 1/1/19.
//  Copyright © 2019 SapratigsMAC1. All rights reserved.
//

import Foundation

var EnDic = [

    "ksclHeyWelcomeBack"        :       "Hey, Welcome Back",
    "ksclDonthaveaccount?"      :       "Don’t have account?",
    "ksclHaveaccount?"          :       "Have account?",
    "ksclForgotPassword"        :       "Forgot Password",
    "ksclBackto"                :       "Back to",
    "ksclHey"                   :       "Hey",
    "ksclWhereyouwanttogo"      :       "Where you want to go?",
    "ksclVacation"              :       "Vacation",
    "ksclTour"                  :       "Tour",
    "ksclEvent"                 :       "Event",
    "ksclFrom"                  :       "From",
    "ksclPerPerson"             :       "Per Person",
    "ksclNights"                :       "Nights",
    "ksclDays"                  :       "Days",
    "ksclVacationIn"            :       "Vacation In",
    "ksclSortBy"                :       "Sort By",
    "ksclFilter"                :       "Filter",
    "ksclPriceRange"            :       "Price Range",
    "ksclDESCRIPTION"           :       "DESCRIPTION",
    "ksclAVAILABILITY"          :       "AVAILABILITY",
    "ksclAMENITIES"             :       "AMENITIES",
    "ksclSTAY"                  :       "STAY",
    "ksclOTHER"                 :       "OTHER",
    "ksclPAYMENTS"              :       "PAYMENTS",
    "ksclWRITEAREVIEW"          :       "WRITE A REVIEW",
    "ksclCONTACTUS"             :       "CONTACT US",
    "ksclStartingfrom"          :       "Starting from",
    "ksclPricenotavailable"     :       "Price not available",
    "ksclNearByRecreationPlaces"    :       "Near By Recreation Places",
    "ksclSuggestedTours"        :       "Suggested Tours",
    "ksclReviews"               :       "Reviews",
    "ksclPlace"                 :       "Place",
    "ksclOpenTime"              :       "Open Time",
    "ksclCloseTime"             :       "Close Time",
    "ksclAddress"               :       "Address",
    "ksclOffice"                :       "Office",
    "ksclPhonenumber"           :       "Phone number",
    "ksclKnowMore"              :       "Know More",
    "ksclOtherActivities"       :       "Other Activities",
    "ksclRatingsReviews"        :       "Ratings & Reviews",
    "ksclREVIEWS"               :       "REVIEWS",
    "ksclGiveStarRating"        :       "Give Star Rating",
    "ksclYourreview"            :       "Your review",
    "ksclBooking"               :       "Booking",
    "ksclDate"                  :       "Date",
    "ksclMidweek"               :       "Midweek",
    "ksclWeekend"               :       "Weekend",
    "ksclDay"                   :       "Day",
    "ksclNight"                 :       "Night",
    "ksclAdult"                 :       "Adult",
    "ksclChild"                 :       "Child",
    "ksclPass"                  :       "Pass",
    "ksclPersonInformation"     :       "Person Information",
    "ksclPerson"                :       "Person",
    "ksclMr"                    :       "Mr",
    "ksclMrs"                   :       "Mrs",
    "ksclMiss"                  :       "Miss",
    "ksclBookingInformation"    :       "Booking Information",
    "ksclVacationDate"          :       "Vacation Date",
    "ksclDayPass"               :       "Day Pass",
    "ksclNightPass"             :       "Night Pass",
    "ksclBookingDate"           :       "Booking Date",
    "ksclBookingID"             :       "Booking ID",
    "ksclPaymentInformation"    :       "Payment Information",
    "ksclTotalPrice"            :       "Total Price",
    "ksclPaymentType"           :       "Payment Type",
    "ksclContactPersonInformation"  :   "Contact Person Information",
    "ksclName"                  :       "Name",
    "ksclDateOfBirth"           :       "Date Of Birth",
    "ksclGender"                :       "Gender",
    "ksclContactNumber"         :       "Contact Number",
    "ksclVACATIONDETAILS"       :       "VACATION DETAILS",
    "ksclINCLUDEDFACILITIES"    :       "INCLUDED FACILITIES",
    "ksclVacationName"          :       "Vacation Name",
    "ksclLocation"              :       "Location",
    "ksclOverview"              :       "Overview",
    "ksclVacationIn"            :       "Vacation In",
    "ksclVacationsIn"           :       "Vacations In",
    "ksclNumberOfPerson"        :       "Number Of Person",
    "ksclContactPerson"         :       "Contact Person",
    "ksclSearch"                :       "Search",
    "ksclTOURCATEGORY"          :       "TOUR CATEGORY",
    "ksclDEPARTURECITY"         :       "DEPARTURE CITY",
    "ksclLOCATIONS"             :       "LOCATIONS",
    "ksclPRICE"                 :       "PRICE",
    "ksclNIGHTS"                :       "NIGHTS",
    "ksclDAYS"                  :       "DAYS",
    "ksclTOURTYPE"             :       "TOUR TYPE",
    "ksclOVERVIEW"              :       "OVERVIEW",
    "ksclITINERARY"             :       "ITINERARY",
    "ksclDeparture"             :       "Departure",
    "ksclLocations"             :       "Locations",
    "ksclDuration"              :       "Duration",
    "ksclSchedule"              :       "Schedule",
    "ksclPerson"                :       "Person",
    "ksclVacationBookingDetails"    :   "Vacation Booking Details",
    "ksclTourBookingDetails"    :       "Tour Booking Details",
    "ksclTourDate"              :       "Tour Date",
    "ksclTOURDETAILS"           :       "TOUR DETAILS",
    "ksclALLPERSONS"            :       "ALL PERSONS",
    "ksclITINERARY"             :       "ITINERARY",
    "ksclTourName"              :       "Tour Name",
    "ksclDepartureFrom"         :       "Departure From",
    "ksclCategory"              :       "Category",
    "ksclPhone"                 :       "Phone",
    "ksclTourIn"                :       "Tour In",
    "ksclToursIn"               :       "Tours In",
    "ksclFree"                  :       "Free",
    "ksclEventType"             :       "Event Type",
    "ksclSuitableFor"           :       "Suitable For",
    "ksclOrganizer"             :       "Organizer",
    "ksclPopularEvents"         :       "Popular Events",
    "ksclOfficeOpenTime"        :       "Office Open Time",
    "ksclOfficeCloseTime"       :       "Office Close Time",
    "ksclEventBookingDetails"   :       "Event Booking Details",
    "ksclEventDate"             :       "Event Date",
    "ksclMale"                  :       "Male",
    "ksclFemale"                :       "Female",
    "ksclNA"                    :       "N/A",
    "ksclEVENTDETAILS"          :       "EVENT DETAILS",
    "ksclEventName"             :       "Event Name",
    "ksclTime"                  :       "Time",
    "ksclEventIn"               :       "Event In",
    "ksclEventsIn"              :       "Events In",
    "ksclHome"                  :       "Home",
    "ksclAccount"               :       "Account",
    "ksclMyBooking"             :       "My Booking",
    "ksclUpcoming"              :       "Upcoming",
    "ksclPast"                  :       "Past",
    "ksclEditProfile"           :       "Edit Profile",
    "ksclChangePassword"        :       "Change Password",
    "ksclSettings"              :       "Settings",
    "ksclLogout"                :       "Logout",
    "ksclUpdate"                :       "Update",
    "ksclGuest"                 :       "Guest",
    
    
    
    "ksctEmail"                 :       "Email",
    "ksctPassword"              :       "Password",
    "ksctEnteryourreviewmaximum200characters"   :   "Enter your review (maximum 200 characters)",
    "ksctFirstname"             :       "First name",
    "ksctLastname"              :       "Last name",
    "ksctMobilenumber"          :       "Mobile number",
    "ksctPassword"              :       "Password",
    "ksctDateofbirth"           :       "Date of birth",
    "ksctGender"                :       "Gender",
    "ksctContactnumber"         :       "Contact number",
    "ksctSearchhere…"           :       "Search here…",
    "ksctCurrentpassword"       :       "Current password",
    "ksctNewpassword"           :       "New password",
    "ksctConfirmpassword"       :       "Confirm password",
    
    
    
    "kscbLoginSignUp"           :       "Login / Sign Up",
    "kscbContinueAsGuest"       :       "Continue As Guest",
    "kscbForgotPassword"        :       "Forgot Password?",
    "kscbCreateaccount"         :       "Create account",
    "kscbLogin"                 :       "Login",
    "kscbSkip"                  :       "Skip",
    "kscbSeeAll"                :       "See All",
    "kscbCLEAR"                 :       "CLEAR",
    "kscbAPPLY"                 :       "APPLY",
    "kscbCLEARFILTER"           :       "CLEAR FILTER",
    "kscbViewOnMap"             :       "View On Map",
    "kscbBookingNA"             :       "Booking N/A",
    "kscbBookNow"               :       "Book Now",
    "kscbSUBMITREVIEW"          :       "SUBMIT REVIEW",
    "kscbOK"                    :       "OK",
    "kscbCANCEL"                :       "CANCEL",
    "kscbContinue"              :       "Continue",
    "kscbPAYNOW"                :       "PAY NOW",
    "kscbYES"                   :       "YES",
    
    
    
    "kscaPleaseenteremail"      :       "Please enter email",
    "kscaPleaseentervalidemail" :       "Please enter valid email",
    "kscaPleaseenterpassword"   :       "Please enter password",
    "kscaPleaseenterfirstname"  :       "Please enter first name",
    "kscaPleaseenterlastname"   :       "Please enter last name",
    "kscaPleaseentermobilenumber"   :   "Please enter mobile number",
    "kscaPleaseentervalidmobilenumber"  :   "Please enter valid mobile number",
    "kscaPleaselogintousethisfeature"   :   "Please login to use this feature",
    "kscaPleaseselectrating"    :   "Please select rating",
    "kscaPleaseenterdescription"    :   "Please enter description",
    "kscaPleaseselectanyonepass"    :   "Please select any one pass",
    "kscaPleaseselect"          :       "Please select",
    "kscatitle"                 :       "title",
    "kscaof"                    :       "of",
    "kscaPleasewaitanddontcloseappwhileweareredirectingyoutopaymentgateway."  : "Please wait and don't close app while we are redirecting you to payment gateway.",
    "kscaPleaseselectdate"      :       "Please select date",
    "kscaAreyousureyouwanttologout" :   "Are you sure you want to logout?",
    "kscaCurrency"              :       "Currency",
    "kscaSelectyourcurrency"    :       "Select your currency",
    "kscaDismiss"               :       "Dismiss",
    "kscaLanguage"              :       "Language",
    "kscaSelectyourlanguage"    :       "Select your language",
    "kscaCountry"               :       "Country",
    "kscaSelectCountry"         :       "Select Country",
    "kscaImportantNote"         :       "Important Note",
    "kscaTermsConditions"       :       "Terms & Conditions",
    
    "abc"  : "abc"
]
